### ISSUE TITLE
I'm so sorry ,my english is pool.but the linuxbrew/brew docker compoes is different 

### ISSUE THREAD

**Issue by goooglethink** [Linuxbrew/brew#662]
theis is my docker compose : eamples:
```
version: '3.3'
services:
  qq:
    image: bestwu/qq:office
    container_name: qq
    devices:
      - /dev/snd
    environment:
      - DISPLAY=unix$DISPLAY
      - AUDIO_GID=29
      - XMODIFIERS=@im=ibus
      - GID=$GID
      - UID=$UID
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ./Templates/TencentFiles:/TencentFiles
```

are you truly you give the docker compose example : 
```
sut:
  build: .
  command: sh -c 'git -C /home/linuxbrew/.linuxbrew/Homebrew fetch --unshallow && brew test-bot'
  environment:
    - GIT_BRANCH
    - GIT_SHA1
    - HOMEBREW_DEVELOPER=1
```
is this ?
